namespace BC2Gescom.Model.OData;

public class SalesInvoiceDTO
{
    public string? odataetag { get; set; }
    public string? no { get; set; }
    public bool allowLineDisc { get; set; }
    public float amount { get; set; }
    public float amountIncludingVAT { get; set; }
    public string? appliesToDocNo { get; set; }
    public string? appliesToDocType { get; set; }
    public string? area { get; set; }
    public string? balAccountNo { get; set; }
    public string? balAccountType { get; set; }
    public string? billToAddress { get; set; }
    public string? billToAddress2 { get; set; }
    public string? billToCity { get; set; }
    public string? billToContact { get; set; }
    public string? billToContactNo { get; set; }
    public string? billToCountryRegionCode { get; set; }
    public string? billToCounty { get; set; }
    public string? billToCustomerNo { get; set; }
    public string? billToName { get; set; }
    public string? billToName2 { get; set; }
    public string? billToPostCode { get; set; }
    public string? cfdiCancellationID { get; set; }
    public string? cfdiCancellationReasonCode { get; set; }
    public string? cfdiExportCode { get; set; }
    public string? cfdiPeriod { get; set; }
    public string? cfdiPurpose { get; set; }
    public string? cfdiRelation { get; set; }
    public string? campaignNo { get; set; }
    public bool cancelled { get; set; }
    public string? certificateSerialNo { get; set; }
    public bool closed { get; set; }
    public bool comment { get; set; }
    public string? companyBankAccountCode { get; set; }
    public bool correction { get; set; }
    public bool corrective { get; set; }
    public bool coupledToDataverse { get; set; }
    public string? createdBy { get; set; }
    public string? creditMemoNo { get; set; }
    public string? currencyCode { get; set; }
    public int currencyFactor { get; set; }
    public int custLedgerEntryNo { get; set; }
    public string? customerDiscGroup { get; set; }
    public string? customerPostingGroup { get; set; }
    public string? customerPriceGroup { get; set; }
    public DateTime dateTimeCancelSent { get; set; }
    public string? dateTimeCanceled { get; set; }
    public string? dateTimeFirstReqSent { get; set; }
    public string? dateTimeSent { get; set; }
    public DateTime dateTimeStampReceived { get; set; }
    public string? dateTimeStamped { get; set; }
    public int dimensionSetID { get; set; }
    public string? directDebitMandateID { get; set; }
    public string? docExchOriginalIdentifier { get; set; }
    public string? documentDate { get; set; }
    public string? documentExchangeIdentifier { get; set; }
    public string? documentExchangeStatus { get; set; }
    public string? draftInvoiceSystemId { get; set; }
    public string? dueDate { get; set; }
    public bool eu3PartyTrade { get; set; }
    public bool electronicDocumentSent { get; set; }
    public string? electronicDocumentStatus { get; set; }
    public string? errorCode { get; set; }
    public string? errorDescription { get; set; }
    public int exchangeRateUSD { get; set; }
    public string? exitPoint { get; set; }
    public string? externalDocumentNo { get; set; }
    public string? fiscalInvoiceNumberPAC { get; set; }
    public bool foreignTrade { get; set; }
    public string? genBusPostingGroup { get; set; }
    public bool getShipmentUsed { get; set; }
    public string? invoiceDiscCode { get; set; }
    public int invoiceDiscountAmount { get; set; }
    public string? invoiceDiscountCalculation { get; set; }
    public int invoiceDiscountValue { get; set; }
    public string? invoiceDistributionList { get; set; }
    public string? languageCode { get; set; }
    public string? locationCode { get; set; }
    public bool markedAsCanceled { get; set; }
    public string? modifiedBy { get; set; }
    public int noPrinted { get; set; }
    public string? noSeries { get; set; }
    public int noOfEDocumentsSent { get; set; }
    public string? onHold { get; set; }
    public string? opportunityNo { get; set; }
    public string? orderConfDistributionList { get; set; }
    public string? orderDate { get; set; }
    public string? orderNo { get; set; }
    public string? orderNoSeries { get; set; }
    public string? pacWebServiceName { get; set; }
    public int paymentDiscount { get; set; }
    public string? paymentMethodCode { get; set; }
    public string? paymentReference { get; set; }
    public int paymentServiceSetID { get; set; }
    public string? paymentTermsCode { get; set; }
    public string? pmtDiscountDate { get; set; }
    public string? postingDate { get; set; }
    public string? postingDescription { get; set; }
    public string? preAssignedNo { get; set; }
    public string? preAssignedNoSeries { get; set; }
    public bool prepaymentInvoice { get; set; }
    public string? prepaymentNoSeries { get; set; }
    public string? prepaymentOrderNo { get; set; }
    public string? priceCalculationMethod { get; set; }
    public bool pricesIncludingVAT { get; set; }
    public string? quoteNo { get; set; }
    public string? reasonCode { get; set; }
    public int remainingAmount { get; set; }
    public string? responsibilityCenter { get; set; }
    public bool reversed { get; set; }
    public int satAddressID { get; set; }
    public string? satInternationalTradeTerm { get; set; }
    public string? steTransactionID { get; set; }
    public string? salespersonCode { get; set; }
    public string? sellToAddress { get; set; }
    public string? sellToAddress2 { get; set; }
    public string? sellToCity { get; set; }
    public string? sellToContact { get; set; }
    public string? sellToContactNo { get; set; }
    public string? sellToCountryRegionCode { get; set; }
    public string? sellToCounty { get; set; }
    public string? sellToCustomerName { get; set; }
    public string? sellToCustomerName2 { get; set; }
    public string? sellToCustomerNo { get; set; }
    public string? sellToEMail { get; set; }
    public string? sellToPhoneNo { get; set; }
    public string? sellToPostCode { get; set; }
    public string? shipToAddress { get; set; }
    public string? shipToAddress2 { get; set; }
    public string? shipToCity { get; set; }
    public string? shipToCode { get; set; }
    public string? shipToContact { get; set; }
    public string? shipToCountryRegionCode { get; set; }
    public string? shipToCounty { get; set; }
    public string? shipToName { get; set; }
    public string? shipToName2 { get; set; }
    public string? shipToPostCode { get; set; }
    public string? shipToUPSZone { get; set; }
    public string? shipmentDate { get; set; }
    public string? shipmentMethodCode { get; set; }
    public string? shippingAgentCode { get; set; }
    public string? shortcutDimension1Code { get; set; }
    public string? shortcutDimension2Code { get; set; }
    public string? sourceCode { get; set; }
    public string? substitutionDocumentNo { get; set; }
    public DateTime systemCreatedAt { get; set; }
    public string? systemCreatedBy { get; set; }
    public string? systemId { get; set; }
    public DateTime systemModifiedAt { get; set; }
    public string? systemModifiedBy { get; set; }
    public string? taxAreaCode { get; set; }
    public string? taxExemptionNo { get; set; }
    public bool taxLiable { get; set; }
    public string? transactionSpecification { get; set; }
    public string? transactionType { get; set; }
    public string? transportMethod { get; set; }
    public string? userID { get; set; }
    public int vatBaseDiscount { get; set; }
    public string? vatBusPostingGroup { get; set; }
    public string? vatCountryRegionCode { get; set; }
    public string? vatRegistrationNo { get; set; }
    public string? vatReportingDate { get; set; }
    public bool webOrder { get; set; }
    public string? yourReference { get; set; }
    public string? digitalStampPACodatamediaEditLink { get; set; }
    public string? digitalStampPACodatamediaReadLink { get; set; }
    public string? digitalStampSATodatamediaEditLink { get; set; }
    public string? digitalStampSATodatamediaReadLink { get; set; }
    public string? originalDocumentXMLodatamediaEditLink { get; set; }
    public string? originalDocumentXMLodatamediaReadLink { get; set; }
    public string? originalStringodatamediaEditLink { get; set; }
    public string? originalStringodatamediaReadLink { get; set; }
    public string? qrCodeodatamediaEditLink { get; set; }
    public string? qrCodeodatamediaReadLink { get; set; }
    public string? signedDocumentXMLodatamediaEditLink { get; set; }
    public string? signedDocumentXMLodatamediaReadLink { get; set; }
    public string? workDescriptionodatamediaEditLink { get; set; }
    public string? workDescriptionodatamediaReadLink { get; set; }
}
